apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c6mr0zbto-nodejs 
  janus-idp.io/tekton: c6mr0zbto-nodejs
  backstage.io/kubernetes-id: c6mr0zbto-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c6mr0zbto-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  